apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80 		default_server;
      listen [::]:80 	default_server;
      return 301 https://$host$request_uri;
    }

    server {
      listen 443		ssl;
      listen [::]:443	ssl;

      ssl_certificate_key /etc/ssl/private/services.key;
      ssl_certificate /etc/ssl/certs/services.crt;

      # error_page 497 https://$host$request_uri;

      location /index.php {
        return 301 https://$host/phpmyadmin/;
      }

      location /wordpress {
        return 307 http://$host:5050/;
      }

      location /phpmyadmin/ {
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://phpmyadmin:5000/;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        # - containerPort: 22
        envFrom:
        - secretRef:
            name: account
        - secretRef:
            name: host-ip
        # livenessProbe:
        #   tcpSocket:
        #     port: 22
        volumeMounts:
        - name: nginx-config
          subPath: default.conf
          mountPath: /etc/nginx/http.d/default.conf
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    # - name: ssh
    #   port: 22