apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-local
          image: influxdb-local
          imagePullPolicy: Never
          ports:
          - containerPort: 8086
          livenessProbe:
            exec:
              command:
                - sh
                - /files/healthy.sh
            initialDelaySeconds: 5
            periodSeconds : 10
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim

