apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name : http
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
