apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-local
          image: mysql-local
          imagePullPolicy: Never
          ports:
          - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - sh
                - /files/healthy.sh
            initialDelaySeconds: 5
            periodSeconds : 10
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

