apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallbADDRESSESsystem
  name: config
data:
  config: |
    addressADDRESSESpools:
    ADDRESSES name: default
      protocol: layer2
      addresses:
      ADDRESSES -