apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name : http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
