apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name : http
      protocol: TCP
      port: 80
      targetPort: 80
    - name : ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name : https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
