apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  
  - name: phpmyadmin
    port: 5000
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_service
        imagePullPolicy: Never
        ports:
        - name: phpmyadmin
          containerPort: 5000
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /startLiveness.sh
          initialDelaySeconds: 30
          periodSeconds: 5